# Generated by Django 2.0.3 on 2018-03-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
    ]
