# Generated by Django 2.0.3 on 2018-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='photo',
            field=models.ImageField(default='noWhinge_Logo.png', upload_to='pictures'),
        ),
    ]
