# Generated by Django 2.0.3 on 2018-04-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintform', '0003_complaints_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='resolved',
            field=models.IntegerField(default=0),
        ),
    ]
