# Generated by Django 2.0.2 on 2018-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintform', '0004_complaints_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='ref_no',
            field=models.CharField(default='nowhinge', max_length=50),
        ),
    ]
